version: "3.2"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
      cache_from:
        - phono/api:latest
    image: phono/api:latest
    container_name: api
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres@db

