version: "3.2"
services:
  phono:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - phono:latest
    image: phono:latest
    container_name: phono
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres@db

