version: "3.2"
services:
  api:
    build:
      context: api/.
      dockerfile: Dockerfile
      cache_from:
        - phono/api:latest
    image: phono/api:latest
    container_name: api
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres@db

  broker:
    build:
      context: broker/
      dockerfile: Dockerfile
      cache_from:
        - phono/broker:latest
    image: phono/broker:latest
    container_name: broker
    ports:
      - "1883:1883"
      - "9001:9001"
