service:
  externalPort: 5000
  internalPort: 5000
deployment:
  containerName: api
  replicas: 2
  image: <<vault>>
  tag: latest
  pullPolicy: Always
  containerPort: 5000
  imagePullSecrets: <<vault>>
