service:
  externalPort: 5000
  internalPort: 5000
deployment:
  containerName: api
  replicas: 2
  image: 088174337422.dkr.ecr.eu-west-1.amazonaws.com/phono/api
  tag: dev-latest
  pullPolicy: Always
  containerPort: 5000
  imagePullSecrets: <<vault>>
