apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app: phono
    release: {{ .Release.Name  }}
spec:
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  - name: {{ .Values.service.portNameTLS }}
    port: {{ .Values.service.externalPortTLS }}
    targetPort: {{ .Values.service.internalPortTLS }}
  selector:
    app: phono
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.PersistentVolumeClaim.pvClaimName }}
  labels:
    app: phono
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.PersistentVolumeClaim.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    app: phono
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: phono
  template:
    metadata:
      annotations:
        timestamp: {{ .Values.timestamp }}
      labels:
        app: phono
        release: {{ .Release.Name  }}
    spec:
      containers:
      - name: {{ .Values.deployment.containerName }}
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        imagePullPolicy: {{ .Values.deployment.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
          name: {{ .Values.deployment.containerPortName }}
        - containerPort: {{ .Values.deployment.containerPortTLS }}
          name: {{ .Values.deployment.containerPortNameTLS }}
        volumeMounts:
        - name: {{ .Values.deployment.volumeMountsName }}
          mountPath: {{ .Values.deployment.volumeMountsMountPath }}
      volumes:
      - name: {{ .Values.deployment.volumesName }}
        persistentVolumeClaim:
          claimName: {{ .Values.deployment.volumesClaimName }}
      imagePullSecrets:
      - name: {{ .Values.deployment.imagePullSecrets }}
