# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  name: phono-service
  type: LoadBalancer
  externalPort: 5000
  internalPort: 5000
configmap:
  name: phono-configmap
deployment:
  name: phono-deployment
  app: phono
image:
  repository: 088174337422.dkr.ecr.eu-west-1.amazonaws.com/phono:latest
  tag: latest
  pullPolicy: Always
resources: {}
