apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"true\"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.phonoHost }}
    - {{ .Values.ingress.collectorHost }}
    secretName: {{ .Values.ingress.secretName }}
  rules:
  - host: {{ .Values.ingress.phonoHost }}
    http:
      paths:
      - backend:
          serviceName: api
          servicePort: {{ .Values.ingress.apiPort }}
        path: /
  - host: {{ .Values.ingress.collectorHost }}
    http:
      paths:
      - backend:
          serviceName: collector
          servicePort: {{ .Values.ingress.collectorPort }}
        path: /
