apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"true\"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.phonoHost }}
    secretName: {{ .Values.ingress.secretName }}
  rules:
  - host: {{ .Values.ingress.phonoHost }}
    http:
      paths:
      - backend:
          serviceName: api
          servicePort: {{ .Values.ingress.apiPort }}
        path: /
      - backend:
          serviceName: collector
          servicePort: {{ .Values.ingress.collectorPort }}
        path: /collector
  - host: {{ .Values.ingress.brokerHost }}
    http:
      paths:
      - backend:
          serviceName: broker
          servicePort: {{ .Values.ingress.brokerPort }}
        path: /
