apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: phono
    release: {{ .Release.Name  }}
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: phono
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: phono
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: phono
  template:
    metadata:
      annotations:
        timestamp: {{ .Values.timestamp }}
      labels:
        app: phono
        release: {{ .Release.Name  }}
    spec:
      containers:
      - name: {{ .Values.deployment.containerName }}
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        imagePullPolicy: {{ .Values.deployment.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
      imagePullSecrets:
      - name: {{ .Values.deployment.imagePullSecrets }}
