apiVersion: apps/v1
kind: Deployment
metadata:
  name: phono-deployment
  labels:
    app: phono
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phono
  template:
    metadata:
      labels:
        app: phono
    spec:
      containers:
      - name: phono
        image: 088174337422.dkr.ecr.eu-west-1.amazonaws.com/phono:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
