service:
  portName: mqtt
  externalPort: 1883
  internalPort: 1883
  nodePort: 30583
  portNameTLS: mqtts
  externalPortTLS: 8883
  internalPortTLS: 8883
  nodePortTLS: 30683
PersistentVolumeClaim:
  pvClaimName: broker-data-claim
  storage: 1Gi
deployment:
  containerName: broker
  replicas: 1
  image: <<vault>>
  tag: latest
  pullPolicy: Always
  containerPort: 1883
  containerPortName: mqtt
  containerPortTLS: 8883
  containerPortNameTLS: mqtts
  volumeMountsName: broker-data-pv
  volumesName: broker-data-pv
  imagePullSecrets: <<vault>>
