apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: phono
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: phono
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: phono
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phono
  template:
    metadata:
      labels:
        app: phono
    spec:
      containers:
      - name: api
        image: 088174337422.dkr.ecr.eu-west-1.amazonaws.com/phono/api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: ecr-registry
